version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10
    branches:
      only:
        - master
    steps:
      - add_ssh_keys:
          fingerprints:
            - "ea:ae:94:da:df:9f:5f:9d:86:ca:dc:97:40:78:ee:2a"
            - "11:12:0c:8a:f5:3a:20:1a:4e:c4:61:d8:2c:28:65:5c"
      - checkout
      - restore_cache:
          keys:
            # fallback to using the latest cache if no exact match is found
            - dependencies-
      - run:
          name: Install
          command: npm i
      - save_cache:
          paths:
            - node_modules
          key: dependencies-
      - run:
          name: build github pages
          command: npm run build
      - run:
          name: Prepare shell commands
          command: chmod +x scripts/deploy.sh
      - run:
          name: setup known hosts1
          command: echo $ipAddress
      - run:
          name: setup known hosts
          command: ssh-keyscan $ipAddress >> ~/.ssh/known_hosts
      - run:
          name: Run deploy scripts
          command: ./scripts/deploy.sh
